### ISSUE TITLE
Running plugin on arena_hardhat_b2a with drop ConVar set to 100 causes fatal server leak

### ISSUE THREAD

**Issue by jack5github** [Fortress-Blast/Fortress-Blast#92]
L 03/27/2021 - 00:26:04: [SM] Exception reported: Handle 419015f is invalid (error 3)
L 03/27/2021 - 00:26:04: [SM] Blaming: fortress_blast.smx
L 03/27/2021 - 00:26:04: [SM] Call stack trace:
L 03/27/2021 - 00:26:04: [SM]   [0] CloseHandle
L 03/27/2021 - 00:26:04: [SM]   [1] Line 2009, D:\tf2server\steamapps\common\Team Fortress 2 Dedicated Server\tf\addons\sourcemod\scripting\fortress_blast.sp::ClearTimer
L 03/27/2021 - 00:26:04: [SM]   [2] Line 740, D:\tf2server\steamapps\common\Team Fortress 2 Dedicated Server\tf\addons\sourcemod\scripting\fortress_blast.sp::OnEntityDestroyed
*DEAD* tinone: pryo
L 03/27/2021 - 00:26:09: [SM] Exception reported: Handle 45d0164 is invalid (error 1)
L 03/27/2021 - 00:26:09: [SM] Blaming: fortress_blast.smx
L 03/27/2021 - 00:26:09: [SM] Call stack trace:
L 03/27/2021 - 00:26:09: [SM]   [0] CloseHandle
L 03/27/2021 - 00:26:09: [SM]   [1] Line 2009, D:\tf2server\steamapps\common\Team Fortress 2 Dedicated Server\tf\addons\sourcemod\scripting\fortress_blast.sp::ClearTimer
L 03/27/2021 - 00:26:09: [SM]   [2] Line 740, D:\tf2server\steamapps\common\Team Fortress 2 Dedicated Server\tf\addons\sourcemod\scripting\fortress_blast.sp::OnEntityDestroyed
L 03/27/2021 - 00:26:12: [SM] Exception reported: Handle 419015f is invalid (error 1)
L 03/27/2021 - 00:26:12: [SM] Blaming: fortress_blast.smx
L 03/27/2021 - 00:26:12: [SM] Call stack trace:
L 03/27/2021 - 00:26:12: [SM]   [0] CloseHandle
L 03/27/2021 - 00:26:12: [SM]   [1] Line 2009, D:\tf2server\steamapps\common\Team Fortress 2 Dedicated Server\tf\addons\sourcemod\scripting\fortress_blast.sp::ClearTimer
L 03/27/2021 - 00:26:12: [SM]   [2] Line 740, D:\tf2server\steamapps\common\Team Fortress 2 Dedicated Server\tf\addons\sourcemod\scripting\fortress_blast.sp::OnEntityDestroyed
L 03/27/2021 - 00:26:13: [SM] Exception reported: Handle 45d0164 is invalid (error 1)
L 03/27/2021 - 00:26:13: [SM] Blaming: fortress_blast.smx
L 03/27/2021 - 00:26:13: [SM] Call stack trace:
L 03/27/2021 - 00:26:13: [SM]   [0] CloseHandle
L 03/27/2021 - 00:26:13: [SM]   [1] Line 2009, D:\tf2server\steamapps\common\Team Fortress 2 Dedicated Server\tf\addons\sourcemod\scripting\fortress_blast.sp::ClearTimer
L 03/27/2021 - 00:26:13: [SM]   [2] Line 740, D:\tf2server\steamapps\common\Team Fortress 2 Dedicated Server\tf\addons\sourcemod\scripting\fortress_blast.sp::OnEntityDestroyed
L 03/27/2021 - 00:26:14: [SM] Exception reported: Handle 419015f is invalid (error 1)
L 03/27/2021 - 00:26:14: [SM] Blaming: fortress_blast.smx
L 03/27/2021 - 00:26:14: [SM] Call stack trace:
L 03/27/2021 - 00:26:14: [SM]   [0] CloseHandle
L 03/27/2021 - 00:26:14: [SM]   [1] Line 2009, D:\tf2server\steamapps\common\Team Fortress 2 Dedicated Server\tf\addons\sourcemod\scripting\fortress_blast.sp::ClearTimer
L 03/27/2021 - 00:26:14: [SM]   [2] Line 740, D:\tf2server\steamapps\common\Team Fortress 2 Dedicated Server\tf\addons\sourcemod\scripting\fortress_blast.sp::OnEntityDestroyed
L 03/27/2021 - 00:26:14: [SM] Exception reported: Handle 47f016c is invalid (error 3)
L 03/27/2021 - 00:26:14: [SM] Blaming: fortress_blast.smx
L 03/27/2021 - 00:26:14: [SM] Call stack trace:
L 03/27/2021 - 00:26:14: [SM]   [0] CloseHandle
L 03/27/2021 - 00:26:14: [SM]   [1] Line 2009, D:\tf2server\steamapps\common\Team Fortress 2 Dedicated Server\tf\addons\sourcemod\scripting\fortress_blast.sp::ClearTimer
L 03/27/2021 - 00:26:14: [SM]   [2] Line 740, D:\tf2server\steamapps\common\Team Fortress 2 Dedicated Server\tf\addons\sourcemod\scripting\fortress_blast.sp::OnEntityDestroyed
L 03/27/2021 - 00:26:15: [SM] Exception reported: Handle 4a1016d is invalid (error 1)
L 03/27/2021 - 00:26:15: [SM] Blaming: fortress_blast.smx
L 03/27/2021 - 00:26:15: [SM] Call stack trace:
L 03/27/2021 - 00:26:15: [SM]   [0] CloseHandle
L 03/27/2021 - 00:26:15: [SM]   [1] Line 2009, D:\tf2server\steamapps\common\Team Fortress 2 Dedicated Server\tf\addons\sourcemod\scripting\fortress_blast.sp::ClearTimer
L 03/27/2021 - 00:26:16: [SM]   [2] Line 888, D:\tf2server\steamapps\common\Team Fortress 2 Dedicated Server\tf\addons\sourcemod\scripting\fortress_blast.sp::player_death
L 03/27/2021 - 00:26:16: [SM] Exception reported: Handle 47f016c is invalid (error 3)
L 03/27/2021 - 00:26:16: [SM] Blaming: fortress_blast.smx
L 03/27/2021 - 00:26:16: [SM] Call stack trace:
L 03/27/2021 - 00:26:16: [SM]   [0] CloseHandle
L 03/27/2021 - 00:26:16: [SM]   [1] Line 2009, D:\tf2server\steamapps\common\Team Fortress 2 Dedicated Server\tf\addons\sourcemod\scripting\fortress_blast.sp::ClearTimer
L 03/27/2021 - 00:26:16: [SM]   [2] Line 740, D:\tf2server\steamapps\common\Team Fortress 2 Dedicated Server\tf\addons\sourcemod\scripting\fortress_blast.sp::OnEntityDestroyed
L 03/27/2021 - 00:26:17: [SM] Exception reported: Handle 45d0164 is invalid (error 1)
L 03/27/2021 - 00:26:17: [SM] Blaming: fortress_blast.smx
L 03/27/2021 - 00:26:17: [SM] Call stack trace:
L 03/27/2021 - 00:26:17: [SM]   [0] CloseHandle
L 03/27/2021 - 00:26:17: [SM]   [1] Line 2009, D:\tf2server\steamapps\common\Team Fortress 2 Dedicated Server\tf\addons\sourcemod\scripting\fortress_blast.sp::ClearTimer
L 03/27/2021 - 00:26:17: [SM]   [2] Line 740, D:\tf2server\steamapps\common\Team Fortress 2 Dedicated Server\tf\addons\sourcemod\scripting\fortress_blast.sp::OnEntityDestroyed
L 03/27/2021 - 00:26:18: [SM] Exception reported: Handle 4a1016d is invalid (error 1)
L 03/27/2021 - 00:26:18: [SM] Blaming: fortress_blast.smx
L 03/27/2021 - 00:26:18: [SM] Call stack trace:
L 03/27/2021 - 00:26:18: [SM]   [0] CloseHandle
L 03/27/2021 - 00:26:18: [SM]   [1] Line 2009, D:\tf2server\steamapps\common\Team Fortress 2 Dedicated Server\tf\addons\sourcemod\scripting\fortress_blast.sp::ClearTimer
L 03/27/2021 - 00:26:18: [SM]   [2] Line 740, D:\tf2server\steamapps\common\Team Fortress 2 Dedicated Server\tf\addons\sourcemod\scripting\fortress_blast.sp::OnEntityDestroyed
L 03/27/2021 - 00:26:18: [SM]   [4] RemoveEntity
L 03/27/2021 - 00:26:18: [SM]   [5] Line 1578, D:\tf2server\steamapps\common\Team Fortress 2 Dedicated Server\tf\addons\sourcemod\scripting\fortress_blast.sp::DeletePowerup
L 03/27/2021 - 00:26:18: [SM]   [6] Line 1574, D:\tf2server\steamapps\common\Team Fortress 2 Dedicated Server\tf\addons\sourcemod\scripting\fortress_blast.sp::OnStartTouchDontRespawn
L 03/27/2021 - 00:26:18: [SM] Exception reported: Stack leak detected: sp:-1126643506 should be 129260!
L 03/27/2021 - 00:26:18: [SM] Exception reported: Not enough space on the heap
L 03/27/2021 - 00:26:18: [SM] Exception reported: Not enough space on the heap
L 03/27/2021 - 00:26:18: [SM] Exception reported: Not enough space on the heap
L 03/27/2021 - 00:26:18: [SM] Exception reported: Not enough space on the stack
L 03/27/2021 - 00:26:18: [SM] Exception reported: Not enough space on the stack
L 03/27/2021 - 00:26:18: [SM] Exception reported: Not enough space on the heap <this line continues forever>

**Comment by Naleksuh** [comment]
please stop creating issues, we have better ways of solving things
