### ISSUE TITLE
Add 16th powerup, from one of the ideas that we've previously discussed

### ISSUE THREAD

**Issue by jack5github** [Fortress-Blast/Fortress-Blast#97]
Launch the user forward and a tiny bit up at maximum speed (Mario Kart 8 Bullet Bill)
Spawn Dispenser at location on ground
Respawn a dead teammate at your location (Super Smash Bros Ultimate Assist Trophy)
Melee only but lots of damage for a short time (Doom Beserk)

**Comment by Naleksuh** [comment]
please stop creating issues, we have better ways of solving things
